name: Deploy to Amazon ECS

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      cluster:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets:
      access-key-id:
        required: true
      secret-access-key:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access-key-id }}
          aws-secret-access-key: ${{ secrets.secret-access-key }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ECR push and ECS deploy
        uses: jaroldwong/ecr-push-and-ecs-deploy@v1
        with:
          ecr-registry: ${{ steps.login-ecr.outputs.registry }}
          ecr-repository: ${{ inputs.repo }}
          ecs-cluster: ${{ inputs.cluster }}
          ecs-service: ${{ inputs.service }}