name: Deploy to Amazon ECS

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      cluster:
        required: true
        type: string
      service:
        required: true
        type: string
      certificate:
        required: false
        type: string
      image-tag:
        required: false
        type: string
        default: 'latest'
    secrets:
      access-key-id:
        required: true
      secret-access-key:
        required: true
      aws-rds-cert:
        required: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download PEM file
        run: |
          curl https://truststore.pki.rds.amazonaws.com/us-west-2/us-west-2-bundle.pem -o us-west-2-bundle.pem -s

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.access-key-id }}
          aws-secret-access-key: ${{ secrets.secret-access-key }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, push to AWS ECR
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ inputs.image-tag }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.repo }}:${{ inputs.image-tag }}

      - name : Force new AWS ECS deployment
        run: |
          aws ecs update-service --cluster ${{ inputs.cluster }} --service ${{ inputs.service }} --force-new-deployment
